com.fasterxml.jackson.*:* = 2.22.1
com.fasterxml.jackson.core:jackson-annotations = 2.22
com.github.ben-manes.caffeine:caffeine = 3.2.4
com.google.guava:guava = 33.6.0-jre
org.ow2.asm:asm-tree = 9.10.1
org.immutables:* = 2.12.2

# Tests
com.google.testing.compile:compile-testing = 0.23.0
com.netflix.nebula:nebula-test = 12.1.0
org.junit:* = 6.1.2
org.junit.jupiter:* = 6.1.2
org.junit.platform:* = 6.1.2
org.assertj:assertj-core = 3.27.7

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.47.0
org.checkerframework:checker-qual = 4.2.2
org.spockframework:* = 2.4-groovy-4.0
